# Application settings
appName: swipe-service
appPort: 8083
debugPort: 8093
replicaCount: 1
springProfile: dev

# Image configuration
image:
  repository: ghcr.io/maxbpro/swipe-service
  tag: latest
  pullPolicy: Always

# Cassandra configuration
cassandraContactPoints: cassandra.soulmate-infra.svc.cluster.local
cassandraPort: 9042
cassandraDataCenter: datacenter1
cassandraKeyspace: swipe
cassandraUsername: cassandra_user
cassandraPassword: cassandra_password

# Keycloak configuration
keycloak:
  issuerUri: http://keycloak.soulmate-infra.svc.cluster.local:8080/realms/customer
  jwkSetUri: http://keycloak.soulmate-infra.svc.cluster.local:8080/realms/customer/protocol/openid-connect/certs

# Service endpoints
services:
  auth:
    url: http://keycloak.soulmate-infra.svc.cluster.local:8080
  users:
    name: http://keycloak.soulmate-infra.svc.cluster.local:8080
  profile:
    url: http://user-service:8082
  swipe:
    url: http://swipe-service:8083
  feed:
    url: http://landmark-service:8084

# Java debug options
javaDebugOptions: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8093"

alloy:
  otlpEndpoint: http://alloy.soulmate-infra.svc.cluster.local:4318
  tracingEndpoint: http://alloy.soulmate-infra.svc.cluster.local:4318/v1/traces