apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName  }}
  labels:
    app: {{ .Values.appName  }}
    component: landmark-service
    managed-by: helm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName  }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        component: landmark-service
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.appPort }}
              protocol: TCP
            - name: debug
              containerPort: {{ .Values.debugPort }}
              protocol: TCP

          env:
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.javaDebugOptions }}

            - name: ELASTICSEARCH_URIS
              value: {{ .Values.elasticSearch.uris }}
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.elasticSearch.secretName }}
                  key: username
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.elasticSearch.secretName }}
                  key: password

            # Kafka
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.kafka.bootstrapServers }}
            - name: KAFKA  # Keep for compatibility
              value: {{ .Values.kafka.bootstrapServers }}

            # Keycloak
            - name: RESOURCE_SERVER_ISSUER_URI
              value: {{ .Values.keycloak.issuerUri | quote }}
            - name: RESOURCE_SERVER_JWK_SET_URI
              value: {{ .Values.keycloak.jwkSetUri | quote }}

            # Service URLs (should be configurable per environment)
            - name: AUTH_API_URL
              value: {{ .Values.services.auth.url  }}
            - name: USERS_API_NAME
              value: {{ .Values.services.users.name }}
            - name: PROFILE_API_URL
              value: {{ .Values.services.profile.url }}
            - name: SWIPE_API_URL
              value: {{ .Values.services.swipe.url }}
            - name: FEED_API_URL
              value: {{ .Values.services.feed.url }}

            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.springProfile }}

            # alloy
            - name: ALLOY_OTLP_ENDPOINT
              value: {{ .Values.alloy.otlpEndpoint | quote }}
            - name: ALLOY_OTLP_TRACING_ENDPOINT
              value: {{ .Values.alloy.tracingEndpoint | quote }}

          # Health check
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.appPort }}
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.appPort }}
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          # Resource limits
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"

{{/*          # Security context (best practice)*/}}
{{/*          securityContext:*/}}
{{/*            allowPrivilegeEscalation: false*/}}
{{/*            readOnlyRootFilesystem: true*/}}
{{/*            runAsNonRoot: true*/}}
{{/*            runAsUser: 1000*/}}
{{/*            capabilities:*/}}
{{/*              drop:*/}}
{{/*                - ALL*/}}
