# Application settings
appName: api-gateway
appPort: 8081
debugPort: 8091
replicaCount: 1
springProfile: dev

# Image configuration
image:
  repository: ghcr.io/maxbpro/soulmate-api-gateway
  tag: latest
  pullPolicy: Always

# Keycloak configuration
keycloak:
  serverUrl: http://keycloak.soulmate-infra.svc.cluster.local:8080
  realm: customer
  clientId: soulmate
  secretName: keycloak-secrets
  authApiUrl: http://keycloak.soulmate-infra.svc.cluster.local:8080

# Service endpoints
services:
  auth:
    url: http://keycloak.soulmate-infra.svc.cluster.local:8080
  users:
    name: http://keycloak.soulmate-infra.svc.cluster.local:8080
  profile:
    url: http://user-service:8082
  swipe:
    url: http://swipe-service:8083
  feed:
    url: http://landmark-service:8084

# Java debug options
javaDebugOptions: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8091"

alloy:
  otlpEndpoint: http://alloy.soulmate-infra.svc.cluster.local:4318
  tracingEndpoint: http://alloy.soulmate-infra.svc.cluster.local:4318/v1/traces